### ISSUE TITLE
Is there is a way to get watchOS apps ?

### ISSUE THREAD

**Issue by m-amr** [facundoolano/app-store-scraper#38]

**Comment by facundoolano** [comment]
Are those apps part of itunes? can you link one?

**Comment by m-amr** [comment]
I can found a link for it but the watchOS apps is listed on the app store of apple watch.
I have tried to use `Itunes RSS` and `Itunes search API` but i couldn't found a way to get IOS apps or watchOS apps.

I found that the supporting devices are iPad and Mac only. why you are not supporting iPhone devices ?

```javascript
const device = {
  IPAD: 'iPadSoftware',
  MAC: 'macSoftware',
  ALL: 'software'
};
```

I don't know how website like https://watchaware.com/watch-apps can get these data ?

**Comment by facundoolano** [comment]
I have those devices because those are the only ones that work (AFAIK) with the search endpoint we're using for the scraper. I don't think it makes sense to scrape third party websites in this project, if apple isn't mixing the watchOS apps with iOS then probably we shouldn't either.

Closing this, but feel free to comment again if you find a way to get watchOs data from iTunes, and I'll reopen.

**Comment by m-amr** [comment]
I would like to ask can this library get IOS apps ? 

because i can see only theses devices ?

```javascript
const device = {
  IPAD: 'iPadSoftware',
  MAC: 'macSoftware',
  ALL: 'software'
};
```

**Comment by facundoolano** [comment]
I think setting it to IPAD means iOS apps. It's kind of hard to know because it's not well documented by apple. Maybe if you have an example of an iPhone app that's not available for iPad we could confirm.
