### ISSUE TITLE
store.reviews example returning 502 Bad Gateway instead of result

### ISSUE THREAD

**Issue by iksnae** [facundoolano/app-store-scraper#50]
I've tried a few different appIds but all result in same

**Comment by iksnae** [comment]
it looks like it's related to the sort option. removing it resolved the 502 error

**Comment by sm-github** [comment]
I'm getting a 502 as well.  Removing the sort option didn't do anything for me

I'm seeing

```
Web Server Error
Description: The host did not return the document correctly.
```

I was trying to get reviews for instagram.  The URL that your package formed was

https://itunes.apple.com/us/rss/customerreviews/id=389801252/sortby=mostRecent/page=1/xml

sidenote: Switching to JSON does work (at least while i'm posting this).  Maybe if the backup was try JSON if XML fails

https://itunes.apple.com/us/rss/customerreviews/id=389801252/sortBy=mostRecent/page=1/json

**Comment by facundoolano** [comment]
Confirmed. I'll switch back to the json feed then.

**Comment by facundoolano** [comment]
Done, I reverted to the previous implementation, that used the json feed. Note this caused the `date` field of the reviews to be lost (since it wasn't included in json, just xml).

**Comment by sm-github** [comment]
I appreciate you fixing it.  But I was relying on the date to collect new reviews regularly. 

Has this happened before?  Is there any evidence that maybe the xml rss customer reviews feed will start working again?

Or even any documentation that I can read to see if the API changed?  (having a hard time finding anything from apple about _/us/rss/customerreviews_)

**Comment by facundoolano** [comment]
It hasn't happened before. Customer reviews feeds is not documented AFAIK. The only thing I know is that apple has been replacing old feeds, and it's would look as the default is json now ([see here](https://rss.itunes.apple.com/en-us)).

I really can't help with the missing date field. It was weird that it only appeared in the xml in the first place, since the json version looks like a direct translation of the xml. If you ever notice the xml being back up or if you find another source for reviews, we can consider switching to that.
